apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: skillpulse
type: Opaque
data:
  # echo -n "rootpassword123" | base64
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3JkMTIz
  # echo -n "skillpulse123" | base64
  DB_PASSWORD: c2tpbGxwdWxzZTEyMw==
